services:
  - type: web
    name: projex-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projex.settings
      - key: PYTHON_VERSION
        value: 3.13.4
